Arguments:
aoi_uri                    C:/Users/mpinsky/Documents/NatCap/AOI_WestCoast.shp
avg_grid_distance          4
bathymetry_uri             C:\InVEST_3_2_0_x86\Base_Data\Marine\DEMs\global_dem\hdr.adf
discount_rate              .05
foundation_cost            2
global_wind_parameters_uri C:\InVEST_3_2_0_x86\WindEnergy\input\global_wind_energy_parameters.csv
land_polygon_uri           C:\InVEST_3_2_0_x86\Base_Data\Marine\Land\global_polygon.shp
max_depth                  60
max_distance               200000
min_depth                  3
min_distance               0
number_of_turbines         1050
price_table                False
rate_change                0.0
suffix                     _WestCoast1050
turbine_parameters_uri     C:/InVEST_3_2_0_x86/WindEnergy/input/3_6_turbine.csv
valuation_container        True
wind_data_uri              C:/InVEST_3_2_0_x86/WindEnergy/input/Global_EEZ_WEBPAR_90pct_100ms.bin
wind_price                 0.161
workspace_dir              C:\Users\mpinsky\Documents\NatCap\Wind


01/26/2016 16:12:03  root               INFO     Logging will be saved to wind_energy-log-2016-01-26--16_12_03.txt
01/26/2016 16:12:03  root               DEBUG    Loaded the model from invest_natcap.wind_energy.wind_energy
01/26/2016 16:12:03  root               INFO     Executing the loaded model
01/26/2016 16:12:03  root               INFO     Running model version development
01/26/2016 16:12:03  root               INFO     Running InVEST version "3.2.0"
01/26/2016 16:12:03  root               INFO     Python architecture: ('32bit', 'WindowsPE')
01/26/2016 16:12:03  root               INFO     Disk space remaining for workspace: 60.0 B
an exception encountered when logging
01/26/2016 16:12:03  root               INFO     Pointing temporary directory at the workspace at C:\Users\mpinsky\Documents\NatCap\Wind
01/26/2016 16:12:03  root               INFO     Updating os.environ["TMP"]=C:\Users\mpinsky\Documents\NatCap\Wind\tmp to C:\Users\mpinsky\Documents\NatCap\Wind
01/26/2016 16:12:03  root               INFO     Updating os.environ["TEMP"]=C:\Users\mpinsky\Documents\NatCap\Wind\tmp to C:\Users\mpinsky\Documents\NatCap\Wind
01/26/2016 16:12:03  root               INFO     Updating os.environ["TMPDIR"]=C:\Users\mpinsky\Documents\NatCap\Wind\tmp to C:\Users\mpinsky\Documents\NatCap\Wind
01/26/2016 16:12:03  root               INFO     Setting tempfile.tempdir to C:\Users\mpinsky\Documents\NatCap\Wind\tmp
01/26/2016 16:12:03  root               INFO     Starting wind_energy
01/26/2016 16:12:03  invest_natcap.wind_energy.wind_energy DEBUG    Starting the Wind Energy Model
01/26/2016 16:12:03  invest_natcap.wind_energy.wind_energy DEBUG    Biophysical Turbine Parameters: {'loss_parameter': '.05', 'turbines_per_circuit': '8', 'rotor_diameter_factor': '7', 'exponent_power_curve': '2', 'rotor_diameter': '107', 'cut_out_wspd': '25.0', 'turbine_rated_pwr': '3.6', 'air_density': '1.225', 'rated_wspd': '12.5', 'cut_in_wspd': '4.0', 'hub_height': '80', 'air_density_coefficient': '1.194e-4'}
01/26/2016 16:12:03  invest_natcap.wind_energy.wind_energy DEBUG    hub_height : 80
01/26/2016 16:12:03  invest_natcap.wind_energy.wind_energy DEBUG    SCALE_key : Ram-080m
01/26/2016 16:12:03  invest_natcap.wind_energy.wind_energy INFO     Reading in Wind Data
01/26/2016 16:12:03  invest_natcap.wind_energy.wind_energy DEBUG    Entering read_wind_data
01/26/2016 16:12:04  invest_natcap.wind_energy.wind_energy DEBUG    Leaving read_wind_data
01/26/2016 16:12:04  invest_natcap.wind_energy.wind_energy INFO     AOI Provided
01/26/2016 16:12:04  invest_natcap.wind_energy.wind_energy INFO     Create point shapefile from wind data
01/26/2016 16:12:04  invest_natcap.wind_energy.wind_energy DEBUG    Entering wind_data_to_point_shape
01/26/2016 16:12:04  invest_natcap.wind_energy.wind_energy DEBUG    Creating new datasource
01/26/2016 16:12:04  invest_natcap.wind_energy.wind_energy DEBUG    field_list : ['Ram-080m', 'LATI', 'K-010m', 'LONG']
01/26/2016 16:12:04  invest_natcap.wind_energy.wind_energy DEBUG    Creating fields for the datasource
01/26/2016 16:12:04  invest_natcap.wind_energy.wind_energy DEBUG    Entering iteration to create and set the features
01/26/2016 16:12:07  invest_natcap.wind_energy.wind_energy DEBUG    Leaving wind_data_to_point_shape
01/26/2016 16:12:07  invest_natcap.wind_energy.wind_energy DEBUG    Clip and project wind points to AOI
Traceback (most recent call last):
  File "logging\__init__.pyc", line 880, in emit
  File "invest_natcap\iui\executor.pyc", line 237, in write
  File "codecs.pyc", line 688, in write
  File "codecs.pyc", line 352, in write
IOError: [Errno 28] No space left on device
Logged from file wind_energy.pyc, line 1719
01/26/2016 16:12:07  invest_natcap.wind_energy.wind_energy DEBUG    Entering clip_and_reproject_shapefile
Traceback (most recent call last):
  File "logging\__init__.pyc", line 880, in emit
  File "invest_natcap\iui\executor.pyc", line 237, in write
  File "codecs.pyc", line 688, in write
  File "codecs.pyc", line 352, in write
IOError: [Errno 28] No space left on device
Logged from file executor.pyc, line 559
01/26/2016 16:12:07  root               ERROR    ---------------------------------------------------
Traceback (most recent call last):
  File "logging\__init__.pyc", line 880, in emit
  File "invest_natcap\iui\executor.pyc", line 237, in write
  File "codecs.pyc", line 688, in write
  File "codecs.pyc", line 352, in write
IOError: [Errno 28] No space left on device
Logged from file executor.pyc, line 560
01/26/2016 16:12:07  root               ERROR    ---------------------- ERROR ----------------------
Traceback (most recent call last):
  File "logging\__init__.pyc", line 880, in emit
  File "invest_natcap\iui\executor.pyc", line 237, in write
  File "codecs.pyc", line 688, in write
  File "codecs.pyc", line 352, in write
IOError: [Errno 28] No space left on device
Logged from file executor.pyc, line 561
01/26/2016 16:12:07  root               ERROR    ---------------------------------------------------
Traceback (most recent call last):
  File "logging\__init__.pyc", line 880, in emit
  File "invest_natcap\iui\executor.pyc", line 237, in write
  File "codecs.pyc", line 688, in write
  File "codecs.pyc", line 352, in write
IOError: [Errno 28] No space left on device
Logged from file executor.pyc, line 562
01/26/2016 16:12:07  root               ERROR    Error: exception found while running wind_energy
01/26/2016 16:12:07  root               DEBUG    
Traceback (most recent call last):
  File "logging\__init__.pyc", line 880, in emit
  File "invest_natcap\iui\executor.pyc", line 237, in write
  File "codecs.pyc", line 688, in write
  File "codecs.pyc", line 352, in write
IOError: [Errno 28] No space left on device
Logged from file executor.pyc, line 349
01/26/2016 16:12:07  root               DEBUG    Build details
Traceback (most recent call last):
  File "logging\__init__.pyc", line 880, in emit
  File "invest_natcap\iui\executor.pyc", line 237, in write
  File "codecs.pyc", line 688, in write
  File "codecs.pyc", line 352, in write
IOError: [Errno 28] No space left on device
Logged from file executor.pyc, line 357
01/26/2016 16:12:07  root               DEBUG    Interpreter
Traceback (most recent call last):
  File "logging\__init__.pyc", line 880, in emit
  File "invest_natcap\iui\executor.pyc", line 237, in write
  File "codecs.pyc", line 688, in write
  File "codecs.pyc", line 352, in write
IOError: [Errno 28] No space left on device
Logged from file executor.pyc, line 360
01/26/2016 16:12:07  root               DEBUG    Current temp dir: C:\Users\mpinsky\Documents\NatCap\Wind\tmp
Traceback (most recent call last):
  File "logging\__init__.pyc", line 880, in emit
  File "invest_natcap\iui\executor.pyc", line 237, in write
  File "codecs.pyc", line 688, in write
  File "codecs.pyc", line 352, in write
IOError: [Errno 28] No space left on device
Logged from file executor.pyc, line 360
Traceback (most recent call last):
  File "logging\__init__.pyc", line 880, in emit
